version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - './:/var/www/html'
    entrypoint:
      ["php" , "-S", "0.0.0.0:8000"]
  pgsql:
    image: postgres:13
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: 'qwerty123'
      POSTGRES_DB: 'nevosoft'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'qwerty123'
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
volumes:
  dbdata:
    driver: local
